(()=>{
const root=document.getElementById('app');if(!root||!window.KhedmaSupabase)return;
const nav=document.querySelector('nav');const btn=document.createElement('button');btn.id='authBtn';btn.className='nav-btn';btn.textContent='تسجيل الدخول';nav?.appendChild(btn);
const modal=document.createElement('div');modal.id='authModal';modal.style.cssText='position:fixed;inset:0;background:#0008;display:none;place-items:center;z-index:9999;padding:20px';modal.innerHTML=`<div style="background:#fff;max-width:430px;width:100%;border-radius:20px;padding:24px;direction:rtl"><button id="authClose" style="float:left">✕</button><div class="section-head"><h2 id="authTitle">تسجيل الدخول</h2><p class="muted">استعمل بريدك الإلكتروني للدخول إلى Khedma.</p></div><div style="display:grid;gap:12px"><label>نوع الحساب<select id="accountRole"><option value="customer">زبون</option><option value="provider">أجير / مقدم خدمة</option></select></label><label>البريد الإلكتروني<input id="authEmail" type="email" required autocomplete="email"></label><label>كلمة المرور<input id="authPassword" type="password" required minlength="6" autocomplete="current-password"></label><button id="authSubmit" class="primary full">دخول</button><button id="authToggle" class="secondary full">إنشاء حساب جديد</button><p id="authMsg" class="muted"></p></div></div>`;document.body.appendChild(modal);
let signup=false;const email=modal.querySelector('#authEmail'),password=modal.querySelector('#authPassword'),role=modal.querySelector('#accountRole'),msg=modal.querySelector('#authMsg');
function open(){modal.style.display='grid';msg.textContent='';}function close(){modal.style.display='none';}function update(){modal.querySelector('#authTitle').textContent=signup?'إنشاء حساب':'تسجيل الدخول';modal.querySelector('#authSubmit').textContent=signup?'إنشاء الحساب':'دخول';modal.querySelector('#authToggle').textContent=signup?'لدي حساب بالفعل':'إنشاء حساب جديد';}
btn.onclick=open;modal.querySelector('#authClose').onclick=close;modal.querySelector('#authToggle').onclick=()=>{signup=!signup;update();};
modal.querySelector('#authSubmit').onclick=async()=>{msg.textContent='⏳ جاري المعالجة...';try{let r;if(signup){r=await KhedmaSupabase.auth.signUp({email:email.value,password:password.value,options:{data:{role:role.value}}});if(r.error)throw r.error;msg.textContent=r.data.session?'تم إنشاء الحساب وتسجيل الدخول.':'تم إنشاء الحساب. تحقق من بريدك الإلكتروني إذا طُلب ذلك.';}else{r=await KhedmaSupabase.auth.signInWithPassword({email:email.value,password:password.value});if(r.error)throw r.error;msg.textContent='تم تسجيل الدخول بنجاح ✅';setTimeout(close,700);}refresh();}catch(e){msg.textContent='❌ '+(e.message||'تعذر إتمام العملية');}};
async function refresh(){const {data}=await KhedmaSupabase.auth.getUser();if(data.user){btn.textContent='حسابي / خروج';btn.onclick=async()=>{await KhedmaSupabase.auth.signOut();refresh();};}else{btn.textContent='تسجيل الدخول';btn.onclick=open;}}refresh();
})();
